<?php
namespace app\admin\controller\wechat;

use app\common\controller\Backend;
use EasyWeChat\Foundation\Application;

class index extends Backend{

    protected $config = [
        'debug'  => true,
        'app_id' => 'wxfee56a904babbd88',
        'secret' => 'f1cf6b160ae47a954182c36c65cb75d8',
        'token'  => 'bzspxkkpqg0xt3vfxjywaw3j0xpng2gd',

        // 'aes_key' => null, // 可选

        'log' => [
            'level' => 'debug',
            'file'  => '/tmp/easywechat.log', // XXX: 绝对路径！！！！
        ],
        'oauth' => [
            'scopes'   => ['snsapi_userinfo'],
            'callback' => '/oauth_callback',
        ],

    ];

    public function _initialize()
    {
        return parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 公众号接入配置
     * @return \think\response\Json|void
     */
    public function index(){

        $app = new Application($this->config);
        $response = $app->server->serve();

        // 将响应输出
        $response->send(); // Laravel 里请使用：return $response;
    }
}