<?php
namespace app\index\controller;

use app\common\controller\Frontend;

class Course extends Frontend{

    protected $noNeedLogin = ['*'];

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 在线课程首页
     */
    public function index(){

        return $this->fetch();
    }
}