<?php
namespace app\index\controller;

use app\common\controller\Frontend;
use think\Db;

class Course extends Frontend{

    protected $noNeedLogin = ['*'];

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 在线课程首页
     */
    public function index(){

        $data = Db::name('course')->order('price asc')->select();

        $this->assign([
            'data' => $data
        ]);
        return $this->fetch();
    }
}