<?php

namespace app\index\controller;

use addons\wechat\library\Config as ConfigService;
use app\common\controller\Frontend;
use EasyWeChat\Foundation\Application;
use think\Config;
use think\Db;
use think\Session;

class Index extends Frontend
{

    protected $noNeedLogin = '*';
    protected $noNeedRight = '*';
    protected $layout = '';

    /**
     * 底部按钮
     * @return string
     * @throws \think\Exception
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @throws \think\exception\DbException
     */
    public function _initialize()
    {
//        if(empty(Session::get('wechat_user'))){
////            Session::set('parent_openid',input('openid',''));//记录分享链接传递过来的父级openid
//            Session::set('topUrl',$_SERVER['REQUEST_URI']);//记录授权前地址
//            header('location:'.'/addons/wechat/index/oauth/openid/');//判断session是否存在  反之跳转授权
//        }
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 首页
     * @return mixed
     */
    public function index(){

        $info = $this->getUserInfo();//获取当前用户信息

        $authstatus = $this->is_auth();//是否认证

        $grade = Db::name('order')
            ->where('user_id',$info['id'])
            ->where('order_status','in','1,2')
            ->alias('o')
            ->join('course c','c.id = o.course_id')
            ->field('type')
            ->find();//查看当前等级

        $is_height = Db::name('order')
                ->where('user_id',$info['id'])
                ->where('order_status','neq','0')
                ->alias('o')
                ->join('course c','c.id = o.course_id')
                ->where('c.type','2')//为2  等于高级用户 则可以免费学习中级
                ->field('type')
                ->find();
        $banner = Db::name('advertising')->select();//首页banner

        $cate = Db::name('category')
            ->where('type','default')
            ->where('pid',0)
            ->select();//首页分类

        $courses = Db::name('course')
            ->alias('ce')
            ->join('category c','c.id = ce.category_id')
            ->where('c.type','course')
            ->where('c.pid',0)
            ->order('ce.weight desc')
            ->field('c.name,ce.*')
            ->select();//课程信息
        $notice = Db::name('notice')->select();
//        dump($courses);
        $course = [];
        foreach ($courses as $k => $v){
            $v['chapter_num'] = count(Db::name('chapter')->where('course_id',$v['id'])->select());//获取当前课程总集数
            $course[] = $v;
        }
        $this->assign([
            'cate' => $cate,
            'banner' => $banner,
            'course' => $course,
            'authstatus' => $authstatus,
            'info' => $info,
            'notice' => $notice,
            'grade' => $grade,
            'is_height' => $is_height
        ]);
        return $this->fetch('home');
    }

    public function news()
    {


        $newslist = [];
        return jsonp(['newslist' => $newslist, 'new' => count($newslist), 'url' => 'https://www.fastadmin.net?ref=news']);
    }


    /**
     * 首页精选材料
     */
    public function show(){

        $id = input('id');
        $info = Db::name('notice')->find($id);
//        dump($info['name']);
        $recommend = Db::name('notice')->where('id','neq',$id)->select();
        $this->assign([
            'info' => $info,
            'recommend' => $recommend
        ]);
        return $this->fetch();
    }

    /**
     * 查询当前用户当前课程 是否购买
     */
    public function isBuy(){
        if(request()->isPost()){
            $res = $this->request->except('s');

            $where = [
                'course_id' => $res['course_id'],
                'user_id' => $res['user_id']
            ];
            $data = Db::name('order')->where($where)->where('order_status','in','1,2')->find();//1为已付款 2为已评价
//            dump($data);

            if($data) return $this->return_msg('200','该用户已购买该产品','','/index/video/index/course_id/'.$res['course_id'].'');

            return $this->return_msg('400','未购买','','/index/video/desc/course_id/'.$res['course_id']);
        }
    }

    public function share(){

        $openid = Session::get('wechat_user')['original']['openid'];
    }
}
