<?php
namespace app\index\controller;

use app\common\controller\Frontend;
use think\Db;
use think\Request;

class Order extends Frontend{

    protected $noNeedLogin = ['*'];

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 全部订单
     * @param int   order_status    付款状态    空则为全部订单
     */
    public function allList(){
        $where = $this->request->request('order_status');
        $data = Db::name('order')
            ->order('createtime desc')
            ->where('order_status',$where)
            ->paginate(10,false,['query' => Request::instance()->request()]);

        return $data;
    }

//    /**
//     * 待付款
//     */
//
//    public function nopayment(){
//
//        $data = Db::name('order')
//            ->order('createtime desc')
//            ->where('order_status',0)
//            ->paginate(10,false,['query' => Request::instance()->request()]);
//
//        return $data;
//    }
//
//    /**
//     * 已付款
//     */
//
//    public function payment(){
//        $data = Db::name('order')
//            ->order('createtime desc')
//            ->where('order_status',1)
//            ->paginate(10,false,['query' => Request::instance()->request()]);
//
//        return $data;
//    }
}