<?php
namespace app\index\controller;

use app\api\controller\Validate;
use app\common\controller\Backend;
use think\Config;
use think\Session;
use think\Db;
use addons\wechat\controller\index;
class Register extends Backend{


    public function _initialize()
    {

        return parent::_initialize(); // TODO: Change the autogenerated stub


    }

    /**
     * @return \think\response\Json|void
     */
    public function index(){

        return $this->fetch();
    }




}