<?php
namespace app\index\controller;


use app\common\controller\Frontend;
use think\Session;

class Sms extends Frontend{

    public function _initialize()
    {
        return parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 获取验证码
     * @param $pnone    手机号
     * @param $template 模板ID
     */
    public function SendSms($phone,$template){

        require './extend/aliyun-dysms-php-sdk/api_demo/SmsDemo.php';

        $code = $this->getNumberCode(6);

        Session::set($phone,$code);//验证码保存到session中
        $sms = new \SmsDemo();
        $sms->SendSms($code,$phone,$template);
    }
}
