<?php
namespace app\index\controller;

use addons\wechat\controller\Index;
use app\common\controller\Frontend;
use think\Config;
use think\Cookie;
use think\Db;
use think\Session;
use think\Validate;

class Userinfo extends Frontend{

    protected $noNeedLogin = ['*'];

    public function _initialize()
    {

        return parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 个人中心首页
     * @return mixed
     */
    public function index(){

        $info = Db::name('userinfo')->where('openid',Session::get('wechat_user')['original']['openid'])->find();

        $auth = '';
        if(!empty($info)) if($info['name'] !='' && $info['phone'] != '') $auth = 1;

        $this->assign([
            'info' => $info,
            'auth' => $auth
        ]);
        return $this->fetch();
    }
    /**
     * 我的名片
     * @param int   id  用户ID
     * @return mixed
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @throws \think\exception\DbException
     */
    public function myinfo(){

        $id = $this->request->request('id');

        $info = Db::name('userinfo')->find($id);

        $this->assign([
            'info' =>$info
        ]);

        return $this->fetch();
    }

    /**
     * 客户资料认证
     * @param int   id      用户ID
     * @param int   phone   手机号
     * @param int   code    验证码
     * @param string    name    姓名
     * @throws \think\Exception
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @throws \think\exception\DbException
     * @throws \think\exception\PDOException
     */
    public function save(){
        $id = $this->request->request('id');
        $user = $this->getUserInfo();
        if(Request()->isPost()){
            $res = $this->request->except('s');
            $rule = [
                'phone|手机号' => 'require',
                'name|姓名' => 'require',
                'code|验证码' => 'require'

            ];

            $validate = new Validate($rule);

            if(!$validate->check($res)) return $this->return_msg(400,$validate->getError());

            if($res['code'] != Cookie::get($res['phone'])) return $this->return_msg(400,'验证码有误，请重新输入！');
            unset($res['code']);//验证完成后删除该字段

            $info = Db::name('userinfo')->update($res);//更新用户信息

            if(!$info) return $this->return_msg(400,'更新失败,请稍后再试...');

            $user = Db::name('userinfo')->field('topid,nickname,name')->find($res['id']);

            if($user['topid'] != 0){
                $parent_info = Db::name('userinfo')->field('openid')->find($user['topid']);//获取父级信息 拿到openid

                if($parent_info){//推送模版消息给当前用户父级

                    $template = $this->site['download_notice'];
                    $url = Config::get('HOST');
                    $data = [
                        'first' => ['客户认证成功通知','#3686c5'],
                        'keyword1' => $user['nickname'].'~'.$user['name'],
                        'keyword2' => date('Y-m-d H:i:s',time()),
                        'remark' => ['您好，您抓潜的客户已通过公众平台进行认证','#3686c5']
                    ];

                    $wechat = new Index();//实例化

                    $wechat->tempMessage($parent_info['openid'],$template,$url,$data);
                }
            }

            return $this->return_msg(200,'认证成功');
        }
        $this->assign([
            'id' => $user['id']
        ]);
        return $this->fetch('auth');
    }

    /**
     * 个人信息完善以及修改
     * $param   int $id     当前用户ID
     * $param   string  $name   姓名
     * $param   int  $card   身份证
     * $param   int  $birth   出生日期
     * $param   string  $avatar   用户头像
     * $param   string  $gender    性别
     * @return mixed
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @throws \think\exception\DbException
     */
    public function infos($id){

//        $id = $this->request->request('id');

        if(!$id) return $this->return_msg(400,'缺少参数');

        $info = Db::name('userinfo')->find($id);
        if(!$info) return $this->return_msg(400,'数据有误');

        if(Request()->isPost()){
            $res = $this->request->except('s');

            $file = $this->upload();

            if($file){
                if($info['avatar']){

                    $url = str_replace('/uploads','uploads',$info['avatar']);

                    if(file_exists($url)) unlink($url);
                }
                $res['avatar'] = $file;
            }

            $rule = [
                'name|姓名' => 'require',
                'card|身份证' => 'require|length:18',
                'birth|出生日期' => 'require'
            ];

            $validate = new Validate($rule);

            if(!$validate->check($res)) return $this->return_msg(400,$validate->getError());

//            dump($res);
            $data = Db::name('userinfo')->update($res);

            if($data) return $this->return_msg(200,'更新成功');


        }

        $this->assign([
            'info' => $info
        ]);
        return $this->fetch();
    }

    /**
     * 投诉建议
     * @param int   user_id 用户ID
     * @param string    name    姓名
     * @param string    contact 联系方式
     * @param string    description 描述
     */
    public function complaint(){
        $user_id = input('user_id');

        if(request()->isPost()){
            $res = $this->request->except('s');

            $rule = [
                'description|描述' => 'require'
            ];
            $validate = new Validate($rule);
            if(!$validate->check($res)) return $this->return_msg(400,$validate->getError());
            $res['createtime'] = time();
//            dump($res);
            $data = Db::name('complaint')->insert($res);

            if($data) return $this->return_msg(200,'发表成功');
        }
        $this->assign([
            'user_id' => $user_id
        ]);
        return $this->fetch();
    }

    /**
     * 分享好友（二维码）
     */
    public function share(){

        $new = new Index();
        $qrcode = $new->qrcode(); //获取推广链接

        $this->assign([
            'qrcode' => $qrcode
        ]);

        return $this->fetch();
    }
    /**
     * 图片上传
     */
    public function upload(){

        $file = $this->request->file('avatar');

        if($file){
            $info = $file->move(ROOT_PATH.'public'.DS.'uploads');

            if($info){
                return '/'.'uploads'.'/'.$info->getSaveName();
            }else{
                $this->error($file->getError());
            }
        }
    }

    /**
     * 我的名片
     */
    public function card($user_id){

        $info = Db::name('userinfo')
            ->where('u.id',$user_id)
            ->alias('u')
            ->join('member_service m','m.id = u.member_service_id')
            ->field('u.*,m.title')
            ->find();
        if($info['member_service_id'] == ''){
            $info = Db::name('userinfo')
                ->where('id',$user_id)
                ->find();
        }
//    dump($user_id);
        $this->assign([
            'info' => $info
        ]);
        return $this->fetch();
    }

}