<?php
namespace app\index\controller;

use app\common\controller\Frontend;
use think\Db;
use think\Session;
use think\Validate;

class Video extends Frontend{

    protected $noNeedLogin = ['*'];

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 视频页
     * @param int   id  课程ID
     */
    public function index(){

        $id = input('course_id');

        $chapter = Db::name('chapter')->where('course_id',$id)->order('weigh desc')->select();//章节

        $chapter_id = input('chapter_id');//播放列表传来的ID

        if(!empty($chapter_id)){
            $one = Db::name('chapter')
                ->where('course_id',$id)
                ->where('id',$chapter_id)
                ->order('weigh desc')
                ->find();//按照降序排序 取默认第一

            $comment = Db::name('comment_chapter')
                ->where('chapter_status',1)
                ->where('course_id',$one['course_id'])
                ->where('chapter_id',$chapter_id)
                ->alias('c')
                ->join('userinfo u','u.id = c.user_id')
                ->field('c.*,u.nickname,u.avatar')
                ->select();//需要增加章节ID判断
        }else{
            $one = Db::name('chapter')
                ->where('course_id',$id)
                ->order('weigh desc')
                ->find();//按照降序排序 取默认第一

            $comment = Db::name('comment_chapter')
                ->where('chapter_status',1)
                ->where('course_id',$one['course_id'])
                ->alias('c')
                ->join('userinfo u','u.id = c.user_id')
                ->field('c.*,u.nickname,u.avatar')
                ->select();//需要增加章节ID判断
        }

        $recommend = Db::name('course')->where('id','neq',$id)->select();//相关推荐

        $user = $this->getUserInfo();//获取当前用户


//        dump($comment);
        $this->assign([
            'chapter' => $chapter,
            'recommend' => $recommend,
            'one' => $one,
            'comment' => $comment,
            'user' => $user
        ]);
        return $this->fetch();
    }


    /**
     *学习感悟（评论）
     * @param int   user_id  用户ID
     * @param int   chapter_id 当前章节ID
     * @param   int course_id   当前课程ID
     * @param   string  content 评论内容
     */
    public function comment(){

        if(Request()->isPost()){
            $res = $this->request->except('s');

            $rule = [
                'content|内容' => 'require'
            ];
            $validate = new Validate($rule);
            if(!$validate->check($res)) return $this->return_msg(400,$validate->getError());
            $user = $this->getUserInfo();//获取当前用户信息
            $res['user_id'] = $user['id'];
            $res['createtime'] = time();
//            dump($res);
            $data = Db::name('comment_chapter')->insert($res);

            if($data) return $this->return_msg(200,'提交成功');
        }
    }
}